chatty:
  security:
    customerUsername: customer
    customerPassword: password
    customerRole: CUSTOMER
    employeeUsername: employee
    employeePassword: password
    employeeRole: EMPLOYEE
    adminUsername: admin
    adminPassword: admin
    adminRole: ACTUATOR

logging:
  level:
    root: INFO

endpoints:
  jmx:
    enabled: true

db:
  url: jdbc:h2:file:./chatty
  username: hrtools
  password: hrtools
  maxPoolSize: 20

server:
  port: 8080